### ISSUE TITLE
关于分工和全栈

### ISSUE THREAD

**Issue by amio** [amio/amio.github.com#13]
有一些还不确定的想法，记下来讨论 @hax 

- __全栈是比分工更美好的形式__  
  更好的整体协调，得到更趋近完美的产品结果，长起来看也是更高的效率。
- __分工是为了提高效率__  
  从最早的人类男打猎女哺乳的分工开始，就是为了提高效率，直到现代社会超级细节的分工方式，这一点依然没变。
- __两个工具：专职 vs 全栈__
  - 在没有专业化的时候，专业化带来最显著的效率提升；
  - 所以可以不停细分，再细分，持续提高效率。
  - （分工有一个潜在问题是引入了沟通成本）
  - 通过细分专业把效率提升到一定阶段会有瓶颈，这个拐点是：沟通负担的提高压过了专业化效率提升的益处
  - 这个拐点之后，向全栈发展会带来更好的成本收益比
  - 全栈在提高质量方面的意义要高过提高效率
  - 全栈需要建立在团队高水平专业化基础上，已经在专业分工提高效率方面达到了拐点
  - 全栈面向的是分工已经达到了足够高的效率之后那些重要不紧急的内容

就现实情况的感受是：
- 身边的全栈代码在跨领域部分代码水平都很低。这个阶段的作品我认为只能算作练习项目，这个阶段的工程师也不能称为全栈工程师。
- 只有练习项目应该给试图成为全栈的工程师实现，因为这个阶段的工程师写出来的代码不但质量低下，而且效率低下——而生产项目既要高效也要高质。

**Comment by hax** [comment]
嗯，我讨论过这个问题：http://www.zhihu.com/question/28207685/answer/41479781

**Comment by amio** [comment]
理念是一致的，
不过实践上不够理想，我困扰的点就在于此吧。

**Comment by hax** [comment]
首先确认fullstack是好的。然后我们需要一些方法去协助fullstack工程师。比如code review、比如各种工具支持、比如好的架构（包括前后端分离）——我个人考虑这一点不是为了分工到人而是为了让一个人在换帽子（即在不同角色和思维方式中转换）的时候很容易。
